apiVersion: v2
name: hypha
description: A Helm chart for deploying Hypha to Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.15.12

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.15.8

dependencies:
  - name: docker-registry
    # condition: docker-registry-mirror.enabled
    version: 2.1.0
    repository: https://helm.twun.io
    condition: docker-registry.enabled
  - name: minio
    version: 3.3.0
    repository: https://charts.min.io/
    condition: minio.enabled
  # - name: tritoninferenceserver
  #   repository: https://helm.ngc.nvidia.com/nvidia
  #   version: 1.0.0
  #   condition: tritoninferenceserver.enabled
  # - name: cert-manager
  #   version: v1.4.2
  #   repository: https://charts.jetstack.io/
  #   condition: cert-manager.enabled
  # - name: ingress-nginx
  #   version: 3.35.0
  #   repository: https://kubernetes.github.io/ingress-nginx
  #   condition: ingress-nginx.enabled
  - name: tritoninferenceserver-hypha
    repository: "file://../tritoninferenceserver-hypha"
    version: 1.0.4
    condition: tritoninferenceserver-hypha.enabled
  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    version: 17.9.4
    condition: redis.enabled