# Default values for imjoy-app-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
acmeEmail: ""
certSecretName: imjoy-app-engine-tls
imjoyHostName: https://hypha.imjoy.io
s3ConsoleHostName: https://hs3c.imjoy.io
s3_endpoint_url_public: https://hs3.imjoy.io
# s3_endpoint_url: ""
auth0_audience: https://imjoy.eu.auth0.com/api/v2/
auth0_domain: imjoy.eu.auth0.com
jwt_secret: "xZ/aDcP+PfoTWgwA9ZADTtU/+djwMeMKz4QlSKRcgEs="

# TODO
# Currently disabled in template because no obvious
# way to pass in the scripts to deployment
startupFunctionsPath: /home/hypha_services/hypha-startup.py
appsDir: /home/hypha-apps
executablePath: /home/bin

image:
  repository: ghcr.io/amun-ai/hypha
  pullPolicy: IfNotPresent
  tag: "0.15.25"

triton_url: "http://tritoninferenceserver.tritoninferenceserver.svc.cluster.local:8000"

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  className: nginx
  path: /
  # Used to create an Ingress record.
  hosts:
    - imjoy.duckdns.org
    # - hypha.imjoy.io
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  # tls:
  # Secrets must be manually created in the namespace.
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

redis:
  fullnameOverride: "redis"
  enabled: true
  global:
    redis:
      password: "admin"

docker-registry:
  enabled: false

minio:
  # nameOverride: "minio"
  fullnameOverride: "minio"
  enabled: true
  rootUser: "minio"
  rootPassword: "minio123"
  publicEndpointUrl: ""
  browserRedirectUrl: ""

  replicas: 4
  ingress:
    enabled: true
    # hosts:
    # - hs3.imjoy.io
  resources:
    requests:
      memory: 2Gi
  persistence:
    size: 10Gi

tritoninferenceserver-hypha:
  enabled: true
  fullnameOverride: "tritoninferenceserver"
  replicaCount: 1
  image:
    imageName: nvcr.io/nvidia/tritonserver:21.10-py3
    pullPolicy: IfNotPresent
    # modelRepositoryPath: s3://imjoy-s3.pasteur.fr:80/model-repository
    modelRepository: /model-repository
    modelStore: /model-repository
    modelSnapshotsPath: /model-snapshots
    numGpus: 0
    # s3Endpoint: https://uk1s3.embassy.ebi.ac.uk
    # s3Bucket: s3://model-repository/
  ingress:
    enabled: false
  # resources:
  #   requests:
  #     nvidia.com/gpu: 1
  #     memory: "32Gi"
  #     cpu: "4"
  #   limits:
  #     nvidia.com/gpu: 1
  #     memory: "32Gi"
  #     cpu: "4"
  resources:
    requests:
      nvidia.com/gpu: 0
      memory: "1Gi"
      cpu: "0.1"
    limits:
      nvidia.com/gpu: 0
      memory: "1Gi"
      cpu: "0.1"

  service:
    type: ClusterIP
