charts:
  # list of charts by name
  # each name should be a directory containing a helm chart
  - name: hypha
    # the prefix to use for built images
    imagePrefix: hypha/k8s-
    # tag to use when resetting the chart values
    # with the --reset flag. It defaults to "set-by-chartpress".
    resetTag: latest
    # version to use when resetting the Chart.yaml's version field with the
    # --reset flag. It defaults to "0.0.1-set.by.chartpress". This is a valid
    # SemVer 2 version, which is required for a helm lint command to succeed.
    resetVersion: 1.2.3
    # The git repo whose gh-pages contains the charts. This can be a local
    # path such as "." as well but if matching <organization>/<repo> will be
    # assumed to be a separate GitHub repository.
    repo:
      git: hypha/helm-chart
      published: https://imjoy.github.io/helm-chart
    # Additional paths that when modified should lead to an updated Chart.yaml
    # version, other than the chart directory in <chart name> or any path that
    # influence the images of the chart. These paths should be set relative to
    # chartpress.yaml's directory.
    # paths:
    #   - ../setup.py
    #   - ../binderhub
    # # images to build for this chart (optional)
    # # images:
    # #   hypha:
    # #     # imageName overrides the default name of the image. The default name
    # #     # is the imagePrefix augmented with the key of this configuration. It
    # #     # would be jupyterhub/k8s-binderhub in this case.
    # #     imageName: imjoy/hypha
    # #     # Build arguments to be passed using docker's --build-arg flag as
    # #     # --build-arg <key>=<value>. TAG and LAST_COMMIT are expandable.
    # #     # buildArgs:
    # #       # MY_STATIC_BUILD_ARG: "hello world"
    # #       # MY_DYNAMIC_BUILD_ARG: "{TAG}-{LAST_COMMIT}"
    # #     # contextPath is the path to the directory that is to be considered the
    # #     # current working directory during the build process of the Dockerfile.
    # #     # This is by default the folder of the Dockerfile. This path should be
    # #     # set relative to chartpress.yaml.
    # #     contextPath: ..
    # #     # By default, changes to the contextPath will make chartpress rebuild
    # #     # the image, but this option make that configurable.
    # #     rebuildOnContextPathChanges: false
    # #     # Path to the Dockerfile, relative to chartpress.yaml. Defaults to
    # #     # "images/<image name>/Dockerfile".
    # #     dockerfilePath: .../Dockerfile
    # #     # Path(s) in <chart name>/values.yaml to be updated with image name and
    # #     # tag.
    # #     # valuesPath:
    # #       # - singleuser.image
    # #       # - singleuser.profileList.0.kubespawner_override.image
    # #     # Additional paths, relative to chartpress.yaml's directory, that should
    # #     # be used to indicate that a new tag of the image is required, aside
    # #     # from the contextPath and dockerfilePath for building the image itself.
    # #     paths:
    # #       - assets
    # #     # If chartpress is used to build images for multiple architectures but
    # #     # not all of those architectures are supported by an image they can be
    # #     # skipped
    # #     skipPlatforms:
    # #       - linux/arm64