apiVersion: v1
kind: Service
metadata:
  name: {{ template "hypha.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    {{- include "hypha.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port:  {{ .Values.service.port}}
      targetPort: "http"