replicaCount: 1
image:
  imageName: nvcr.io/nvidia/tritonserver:23.08-py3
  pullPolicy: IfNotPresent
  # modelRepositoryPath: s3://imjoy-s3.pasteur.fr:80/model-repository
  modelSnapshots: /model-snapshots
  modelRepository: /model-repository
  modelStore: /model-repository
  s3Endpoint: ""
  s3Bucket: ""
  env:
  - name: TF_FORCE_GPU_ALLOW_GROWTH
    value: "true"


ingress:
  enabled: false
  className: nginx
  path: /
  # Used to create an Ingress record.
  hosts: []
  name: tritoninferenceserver
  type: ClusterIP
  port: 8000
  annotations: {}

resources:
  requests:
    nvidia.com/gpu: 0
    memory: "2Gi"
    cpu: "1"
  limits:
    nvidia.com/gpu: 0
    memory: "3Gi"
    cpu: "1"

service:
  name: tritoninferenceserver
  port: 8000
  type: ClusterIP
  annotations: {}
  loadBalancerIP: ""
  loadBalanagerSourceRanges: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  nodePort: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  gpuUtilization: 50
#   gpuMemoryUtilization: 50

nodeSelector: {}
podLabels: {}
securityContext: {}

readinessProbe:
  httpGet:
    path: /v2/health/ready
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /v2/health/live
    port: 8000
  initialDelaySeconds: 1800
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

initContainers: []

# - name: copy-models
#   image: alpine
#   command: ["/bin/sh", "-c"]
#   args:
#   - cp -r server/docs/examples/model_repository/ /model-repository

volumes:
- emptyDir:
    medium: Memory
  name: dshm
- ephemeral:
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        # storageClassName: standard-rwo
        volumeMode: Filesystem
  name: triton-cache
volumeMounts:
- mountPath: /dev/shm
  name: dshm
- mountPath: /opt/tritonserver/caches
  name: triton-cache
  subPath: caches
- mountPath: /model-repository
  name: triton-cache
  subPath: model-repository
- mountPath: /model-snapshots
  name: triton-cache
  subPath: model-snapshots
- mountPath: /tmp
  name: triton-cache
