name: Helm

on:
  push:
    branches:
      - main
      - master
  pull_request: ~

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: KinD (Kubernetes in Docker) Action
        uses: helm/kind-action@v1.3.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: kubectl
        run: kubectl get pods -A
      # - run: sudo apt-get update && sudo apt-get install iptables -y
      # - uses: WyriHaximus/github-action-helm3@v2
      - name: Install Helmsman
        run: 'wget -c https://github.com/Praqma/helmsman/releases/download/v3.8.1/helmsman_3.8.1_linux_amd64.tar.gz -O - | tar -xz -C /usr/local/bin/'
        # - run: which helmsman
        # - run: ls /usr/local/bin/
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.3
      # - uses: actions/setup-node@v2
        # - uses: actions/setup-python@v2
      # See https://github.com/helm/chart-testing/blob/main/doc/ct_install.md
      - name: Run chart-testing (install)
        run: ct install --config ct.yaml --debug
  



